using System;
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace Loby.AspNetCore.Services.Models
{
    /// <summary>
    /// Provide some information about an action in a <see cref="Controller"/>.
    /// </summary>
    public class ControllerActionInfo
    {
        /// <summary>
        /// An string representing the actual name of action.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// An string representing a display name for an action.
        /// </summary>
        /// <remarks>
        /// Display name could be provided by using <see cref="DisplayNameAttribute"/>.
        /// </remarks>
        public string DisplayName { get; set; }

        /// <summary>
        /// A flag that specifies the current action is protected or not.
        /// </summary>
        /// <remarks>
        /// Protection could be done by using <see cref="AuthorizeAttribute"/>.
        /// </remarks>
        public bool IsSecured { get; set; }

        /// <summary>
        /// An string representing an id that generated by combination of 
        /// area name, controller name and action name.
        /// </summary>
        /// <remarks>
        /// Pattern: AreaName:ControllerName:ActionName
        /// </remarks>
        public string Id => $"{ControllerId}:{Name}".ToLower();

        /// <summary>
        /// An string representing unique id for the controller that the 
        /// current action is defined in it.
        /// For more information see <see cref="ControllerInfo.Id"/>.
        /// </summary>
        public string ControllerId { get; set; }

        /// <summary>
        /// A list that contains all the custom attributes applied to the current action.
        /// </summary>
        public IList<Attribute> Attributes { get; set; }
    }
}
